apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: backend
    component: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      component: backend-api
  template:
    metadata:
      labels:
        app: ecommerce
        tier: backend
        component: backend-api
    spec:
      containers:
        - name: backend
          image: user:1.0
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@db:5432/mydb
            - name: REDIS_URL
              value: redis://redis:6379/0
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: backend
    component: backend-api
spec:
  selector:
    component: backend-api
  ports:
    - port: 8000
      targetPort: 8000
