apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: backend
    component: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      component: cart-service
  template:
    metadata:
      labels:
        app: ecommerce
        tier: backend
        component: cart-service
    spec:
      containers:
        - name: cart
          image: cart:1.0
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: backend
    component: cart-service
spec:
  selector:
    component: cart-service
  ports:
    - port: 5000
      targetPort: 5000
