apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command:
            ['sh', '-c', 'until nc -z mongo 27017; do echo waiting for mongo; sleep 2; done;']
      containers:
        - name: cart
          image: mohan14242ai/cart:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/mycartdb
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: app-namespace
spec:
  selector:
    app: cart
  ports:
    - port: 5000
      targetPort: 5000