apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: db
    component: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      component: postgres-db
  template:
    metadata:
      labels:
        app: ecommerce
        tier: db
        component: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: mydb
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: db
    component: postgres-db
spec:
  selector:
    component: postgres-db
  ports:
    - port: 5432
      targetPort: 5432
