apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: db
    component: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      component: postgres-db
  template:
    metadata:
      labels:
        app: ecommerce
        tier: db
        component: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: mydb
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: db
    component: postgres-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: db
    component: postgres-db
spec:
  selector:
    component: postgres-db
  ports:
    - port: 5432
      targetPort: 5432
