apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: frontend
    component: frontend-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      component: frontend-ui
  template:
    metadata:
      labels:
        app: ecommerce
        tier: frontend
        component: frontend-ui
    spec:
      containers:
        - name: frontend
          image: mohan14242ai/front:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-namespace
spec:
  type: NodePort
  selector:
    app: ecommerce
    component: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31234  # Optional: choose a static port between 30000-32767
