apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: mohan14242ai/order:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@db1:5432/mydb
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: app-namespace
spec:
  selector:
    app: order
  ports:
    - port: 8080
      targetPort: 8080