apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: backend
    component: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      component: payment-service
  template:
    metadata:
      labels:
        app: ecommerce
        tier: backend
        component: payment-service
    spec:
      containers:
        - name: payment
          image: mohan14242ai/payment:1.0
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: backend
    component: payment-service
spec:
  selector:
    component: payment-service
  ports:
    - port: 8081
      targetPort: 8081
