apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: cache
    component: redis-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      component: redis-cache
  template:
    metadata:
      labels:
        app: ecommerce
        tier: cache
        component: redis-cache
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: app-namespace
  labels:
    app: ecommerce
    tier: cache
    component: redis-cache
spec:
  selector:
    component: redis-cache
  ports:
    - port: 6379
      targetPort: 6379
